spring:
  application:
    name: spring-data-jpa
  datasource:
    url: jdbc:postgresql://localhost:5432/student_db
    username: postgres
    password: 5804
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true # For development only or else you will get fired
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    property-naming-strategy: SNAKE_CASE